### PR TITLE
Add compabitility with WSL

### PR DESCRIPTION
**Pull request by thijsputman**
WSL (Windows Subsystem for Linux) presents itself as "Linux" in Node, but in order for a desktop application to be opened, requires the Windows-approach (i.e. calling `cmd.exe`).

This pull-request aims to detect this (peculiar? 😉) situation by looking at the value of `os.release()` and in that case following the Windows-approach. This required some minor modifications to the overall flow of the code.

Tested on physical Windows, Windows+WSL, Mac and Linux systems.

### CODE REVIEW

**Comment by domenic** [comment]
Hmm, interesting!!

The thing I'd worry about here is what about people using `opener` in WSL to open Linux binaries and the like? I guess it'll probably still work?

**Comment by thijsputman** [comment]
Fair point; that wouldn't work anymore (they'll be piped through to `cmd.exe` which doesn't know anything about the Linux environment the call came from).

On the other hand: On Linux you're using `xdg-open`, which - as far as I know - is intended to open a file/URL via the default application in the X11 system (i.e. open desktop application). That'll never work on WSL to begin with (as there's no formal X11 support; you could hack it together, but Microsoft's official stated purpose of WSL is to run command-line tools).

**Comment by domenic** [comment]
That's a solid point, thanks! I'm convinced.

This has style issues that I need to clean up before merging. My bad for having such out of date lint technology. But I'll try to do that soon (and add eslint) and then merge and release.

**Comment by thijsputman** [comment]
Perfect; thanks a lot!

**Pull request merged**
